language: node_js
node_js:
  - "node"

script:
  - bash ./deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "de8b5a0f10ef"
    - COMMIT_AUTHOR_EMAIL: "cam@mcc.id.au"
notifications:
  email:
    on_success: never
    on_failure: always
