language: node_js
node_js:
  - "node"

script:
  - bash ./deploy.sh

deploy:
  local_dir: out/
  target_branch: gh-pages
  keep_history: true
  provider: pages
  skip_cleanup: true
  github_token: $GH_ACCESS_TOKEN
  committer_from_gh: true
  on:
    branch: main

notifications:
  email:
    on_success: never
    on_failure: always
